version: '3.8'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432"
    volumes:
      - ./home/db:/var/lib/postgresql/data:z

  web:
    build: ./back
    restart: unless-stopped
    command: >
      bash -c "python /home/back/manage.py check
      && python /home/back/manage.py migrate
      && python /home/back/manage.py runserver 0.0.0.0:8000"
    env_file:
      - back/TestTaskLearningResource/.env
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./back:/home/back
    links:
      - db
    depends_on:
      - db