# Generated by Django 3.2 on 2021-04-10 17:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('deadline', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), verbose_name='deadline')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homework.homework', verbose_name='homework')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0, verbose_name='mark')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homework.homework', verbose_name='homework')),
                ('homework_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homework.homeworkanswer', verbose_name='homework_answer')),
            ],
        ),
    ]
