# Generated by Django 3.2 on 2021-04-11 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0002_auto_20210410_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='file',
            field=models.FilePathField(validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
