# Generated by Django 3.2 on 2021-04-11 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0003_alter_homeworkanswer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
