# Generated by Django 3.2 on 2021-04-11 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0004_alter_homeworkanswer_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Homework', 'verbose_name_plural': 'Homeworks'},
        ),
        migrations.AlterModelOptions(
            name='homeworkanswer',
            options={'verbose_name': 'HomeworkAnswer', 'verbose_name_plural': 'HomeworkAnswers'},
        ),
        migrations.AlterModelOptions(
            name='homeworkmark',
            options={'verbose_name': 'HomeworkMark', 'verbose_name_plural': 'HomeworkMarks'},
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='file',
            field=models.FileField(default=None, upload_to='homework_txt/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
