# Generated by Django 3.2 on 2021-04-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0005_auto_20210411_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkmark',
            name='explanation',
            field=models.TextField(default='', verbose_name='explanation'),
        ),
    ]
