# Generated by Django 3.2 on 2021-04-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0006_homeworkmark_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='file',
            field=models.TextField(verbose_name='file_path'),
        ),
    ]
