# Generated by Django 3.2 on 2021-04-12 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0008_alter_homeworkanswer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmark',
            name='homework',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Homework.homework', verbose_name='homework'),
        ),
        migrations.AlterField(
            model_name='homeworkmark',
            name='homework_answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Homework.homeworkanswer', verbose_name='homework_answer'),
        ),
    ]
