# Generated by Django 3.2 on 2021-04-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0009_auto_20210412_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmark',
            name='mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
    ]
