# Generated by Django 3.2 on 2021-04-14 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Homework', '0010_alter_homeworkmark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), help_text='Homework deadline', verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='text',
            field=models.TextField(help_text='Homework condition', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='file',
            field=models.CharField(help_text='The path to the file attached to the homework', max_length=256, verbose_name='FilePath'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='homework',
            field=models.ForeignKey(help_text='Homework identifier', on_delete=django.db.models.deletion.CASCADE, to='Homework.homework', verbose_name='Homework'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='student',
            field=models.ForeignKey(default=None, help_text='Student who completed homework', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='homeworkmark',
            name='explanation',
            field=models.TextField(default='', help_text='Explanation why student got this mark', verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='homeworkmark',
            name='homework',
            field=models.ForeignKey(default=None, help_text='Homework', on_delete=django.db.models.deletion.CASCADE, to='Homework.homework', verbose_name='Homework'),
        ),
        migrations.AlterField(
            model_name='homeworkmark',
            name='homework_answer',
            field=models.ForeignKey(default=None, help_text='The answer to which we are assessing', on_delete=django.db.models.deletion.CASCADE, to='Homework.homeworkanswer', verbose_name='HomeworkAnswer'),
        ),
        migrations.AlterField(
            model_name='homeworkmark',
            name='mark',
            field=models.FloatField(default=0.0, help_text='Mark', verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='homeworkmark',
            name='student',
            field=models.ForeignKey(default=None, help_text='The student who gets the mark', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
