# Generated by Django 3.2 on 2021-04-11 16:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('deadline', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), verbose_name='deadline')),
                ('sphere', models.CharField(help_text='Question specific', max_length=32, verbose_name='sphere')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_count', models.IntegerField(default=None)),
                ('wrong_count', models.IntegerField(default=None)),
                ('mark', models.FloatField(default=0.0, verbose_name='mark')),
                ('result_owner', models.ForeignKey(help_text='Result owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='result_owner')),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Test.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('question_value', models.FloatField(default=None)),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Test.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Test.testquestions')),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Test.test')),
            ],
        ),
    ]
